name: ${name}
version: ${version}
main: ${main}
load: STARTUP
authors: [ CocoTheOwner ]
website: codevs.nl
description: Decree command system
commands:
  command:
    aliases: [ cmmd, cmd, cd ]
api-version: ${apiversion}
hotload-dependencies: false